- name: date
  key: d
  cmd: date
  confirm: true
  clear: true

- name: fzf (intentionally very long task name)
  key: f
  cmd: fzf
  args: [--preview, "bat {}"]

- name: fail
  key: f
  cmd: false

- name: vim
  key: v
  cmd: nvim

- name: cargo run
  key: R
  cmd: cargo
  args: [run]
